name: Hiç Arts
favicon: null
layout_spectrum: 0.34593844087794423
typography_spectrum: 0.39779111789539456
title: Hiç Arts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7554691559635103
  lightness: 0.6798481573350728
  saturation: 0.9285719871986657
  rhythmicContrast: 0.736274030758068
purpose: []
